### ISSUE TITLE
[BUG] Incompatibility with third-party sheet types

### ISSUE THREAD

**Issue by lisosaurus** [dmrickey/fvtt-ckl-roll-bonuses#42]
**Describe the bug**
This module breaks third-party actor sheet types, such as [PF1 Caravans](https://github.com/KitCat420/pf1e-caravans).

**To Reproduce**
1. Add a third-party actor sheet module, such as the one listed above
2. Create an actor with this new actor sheet type
3. Try to add anything to the new actor
4. See errors

**Example of Errors**
```js
TypeError: Error thrown in hooked function '' for hook 'renderActorSheetPF'. Cannot read properties of undefined (reading 'versatile-performance')
[Detected 2 packages: ckl-roll-bonuses, system:pf1]
    at flag-helpers.mjs:234:57
    at Array.forEach (<anonymous>)
    at flag-helpers.mjs:232:27
    at EmbeddedCollection.forEach (commons.js:4213:9)
    at new KeyedDFlagHelper (flag-helpers.mjs:222:21)
    at Object.fn (versatile-performance.mjs:124:20)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at CaravanSheet._render (foundry.js:5855:13)
    at async CaravanSheet._render (foundry.js:6532:5)
    at async CaravanSheet._render (actor-sheet.mjs:3795:11)

TypeError: Error thrown in hooked function '' for hook 'renderItemSheet'. Cannot read properties of undefined (reading 'weapon-specialization')
[Detected 1 package: ckl-roll-bonuses]
    at Object.fn (weapon-specialization.mjs:113:81)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at WagonSheet._render (foundry.js:5855:13)
    at async WagonSheet._render (foundry.js:6532:5)
```

**What version of Roll Bonuses and PF1 are you using?**
Roll Bonuses: 2.14.4
core: 10.7

**Comment by dmrickey** [comment]
Fixed in 2.15.0
